/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as MonRendezVousRouteImport } from './routes/mon-rendez-vous'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminEmployeesRouteImport } from './routes/admin.employees'
import { Route as AdminPrestationsRouteImport } from './routes/admin.prestations'
import { Route as AdminRendezVousRouteImport } from './routes/admin.rendez-vous'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const MonRendezVousRoute = MonRendezVousRouteImport.update({
  id: '/mon-rendez-vous',
  path: '/mon-rendez-vous',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEmployeesRoute = AdminEmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPrestationsRoute = AdminPrestationsRouteImport.update({
  id: '/prestations',
  path: '/prestations',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRendezVousRoute = AdminRendezVousRouteImport.update({
  id: '/rendez-vous',
  path: '/rendez-vous',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/mon-rendez-vous': typeof MonRendezVousRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/employees': typeof AdminEmployeesRoute
  '/admin/prestations': typeof AdminPrestationsRoute
  '/admin/rendez-vous': typeof AdminRendezVousRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/mon-rendez-vous': typeof MonRendezVousRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/employees': typeof AdminEmployeesRoute
  '/admin/prestations': typeof AdminPrestationsRoute
  '/admin/rendez-vous': typeof AdminRendezVousRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/mon-rendez-vous': typeof MonRendezVousRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/employees': typeof AdminEmployeesRoute
  '/admin/prestations': typeof AdminPrestationsRoute
  '/admin/rendez-vous': typeof AdminRendezVousRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/mon-rendez-vous'
    | '/admin/dashboard'
    | '/admin/employees'
    | '/admin/prestations'
    | '/admin/rendez-vous'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/mon-rendez-vous'
    | '/admin/dashboard'
    | '/admin/employees'
    | '/admin/prestations'
    | '/admin/rendez-vous'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/mon-rendez-vous'
    | '/admin/dashboard'
    | '/admin/employees'
    | '/admin/prestations'
    | '/admin/rendez-vous'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  MonRendezVousRoute: typeof MonRendezVousRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mon-rendez-vous': {
      id: '/mon-rendez-vous'
      path: '/mon-rendez-vous'
      fullPath: '/mon-rendez-vous'
      preLoaderRoute: typeof MonRendezVousRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/employees': {
      id: '/admin/employees'
      path: '/employees'
      fullPath: '/admin/employees'
      preLoaderRoute: typeof AdminEmployeesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/prestations': {
      id: '/admin/prestations'
      path: '/prestations'
      fullPath: '/admin/prestations'
      preLoaderRoute: typeof AdminPrestationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/rendez-vous': {
      id: '/admin/rendez-vous'
      path: '/rendez-vous'
      fullPath: '/admin/rendez-vous'
      preLoaderRoute: typeof AdminRendezVousRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminEmployeesRoute: typeof AdminEmployeesRoute
  AdminPrestationsRoute: typeof AdminPrestationsRoute
  AdminRendezVousRoute: typeof AdminRendezVousRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminDashboardRoute: AdminDashboardRoute,
  AdminEmployeesRoute: AdminEmployeesRoute,
  AdminPrestationsRoute: AdminPrestationsRoute,
  AdminRendezVousRoute: AdminRendezVousRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  MonRendezVousRoute: MonRendezVousRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
